services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'

  App\Security\DatabaseUserProvider:
    arguments:
      $entityManager: '@Doctrine\ORM\EntityManagerInterface'

  Doctrine\ORM\EntityManagerInterface:
    factory: ['App\Doctrine\EntityManagerFactory', 'create']
    arguments:
      $databaseUrl: '%env(resolve:DATABASE_URL)%'
      $projectDir: '%kernel.project_dir%'
      $environment: '%kernel.environment%'
