apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghiseul-cetateanului

resources:
  - ../../base

commonLabels:
  app.kubernetes.io/part-of: documents-manager
  app.kubernetes.io/managed-by: argocd
