
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ghiseul-cetateanului
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
